// Copyright 2015 The go-ethereum Authors
// This file is part of the go-ethereum library.
//
// The go-ethereum library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The go-ethereum library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the go-ethereum library. If not, see <http://www.gnu.org/licenses/>.

// 版权所有 2015 The go-ethereum Authors
// 此文件是 go-ethereum 库的一部分。
//
// go-ethereum 库是免费软件：您可以根据自由软件基金会发布的 GNU 宽通用公共许可证的条款重新分发和/或修改它，
// 可以是许可证的第 3 版，也可以是（由您选择）任何更高版本。
//
// go-ethereum 库的发布是希望它能有用，但没有任何保证；甚至没有对适销性或特定用途适用性的默示保证。
// 有关更多详细信息，请参阅 GNU 宽通用公共许可证。
//
// 您应该已经随 go-ethereum 库收到一份 GNU 宽通用公共许可证的副本。如果没有，请参阅 <http://www.gnu.org/licenses/>。

package abi

import (
	"fmt"
	"strings"

	"github.com/ethereum/go-ethereum/crypto"
)

// FunctionType represents different types of functions a contract might have.
// FunctionType 表示合约可能具有的不同类型的函数。
type FunctionType int

const (
	// Constructor represents the constructor of the contract.
	// The constructor function is called while deploying a contract.
	// Constructor 表示合约的构造函数。
	// 构造函数在部署合约时被调用。
	Constructor FunctionType = iota
	// Fallback represents the fallback function.
	// This function is executed if no other function matches the given function
	// signature and no receive function is specified.
	// Fallback 表示回退函数。
	// 如果没有其他函数匹配给定的函数签名，并且没有指定 receive 函数，则执行此函数。
	Fallback
	// Receive represents the receive function.
	// This function is executed on plain Ether transfers.
	// Receive 表示接收函数。
	// 此函数在纯以太币转账时执行。
	Receive
	// Function represents a normal function.
	// Function 表示一个普通函数。
	Function
)

// Method represents a callable given a `Name` and whether the method is a constant.
// If the method is `Const` no transaction needs to be created for this
// particular Method call. It can easily be simulated using a local VM.
// For example a `Balance()` method only needs to retrieve something
// from the storage and therefore requires no Tx to be sent to the
// network. A method such as `Transact` does require a Tx and thus will
// be flagged `false`.
// Input specifies the required input parameters for this gives method.
// Method 表示一个可调用的方法，它具有一个“名称”和方法是否为常量的标志。
// 如果方法是“Const”（常量），则无需为此特定方法调用创建交易。
// 它可以轻松地使用本地 VM 进行模拟。
// 例如，一个 `Balance()` 方法只需要从存储中检索某些内容，因此不需要向网络发送交易。
// 像 `Transact` 这样的方法确实需要一个交易，因此将被标记为 `false`。
// Input 指定了此方法所需的输入参数。
type Method struct {
	// Name is the method name used for internal representation. It's derived from
	// the raw name and a suffix will be added in the case of a function overload.
	//
	// e.g.
	// These are two functions that have the same name:
	// * foo(int,int)
	// * foo(uint,uint)
	// The method name of the first one will be resolved as foo while the second one
	// will be resolved as foo0.
	// Name 是用于内部表示的方法名称。它源自原始名称，
	// 在函数重载的情况下会添加后缀。
	//
	// 例如：
	// 这两个函数同名：
	// * foo(int,int)
	// * foo(uint,uint)
	// 第一个函数的方法名将解析为 foo，而第二个
	// 将解析为 foo0。
	Name    string
	RawName string // RawName 是从 ABI 解析的原始方法名称

	// Type indicates whether the method is a
	// special fallback introduced in solidity v0.6.0
	// Type 指示该方法是否是 Solidity v0.6.0 中引入的特殊回退函数
	Type FunctionType

	// StateMutability indicates the mutability state of method,
	// the default value is nonpayable. It can be empty if the abi
	// is generated by legacy compiler.
	// StateMutability 指示方法的可变性状态，
	// 默认值为 nonpayable。如果 abi 是由旧版编译器生成的，则可以为空。
	StateMutability string

	// Legacy indicators generated by compiler before v0.6.0
	// 编译器 v0.6.0 之前生成的旧版指示器
	Constant bool // 是否为常量方法（只读）
	Payable  bool // 是否可支付

	Inputs  Arguments // 输入参数
	Outputs Arguments // 输出参数
	str     string    // 缓存的字符串表示形式
	// Sig returns the methods string signature according to the ABI spec.
	// e.g.		function foo(uint32 a, int b) = "foo(uint32,int256)"
	// Please note that "int" is substitute for its canonical representation "int256"
	// Sig 返回根据 ABI 规范的方法字符串签名。
	// 例如： function foo(uint32 a, int b) = "foo(uint32,int256)"
	// 请注意，“int”会替换为其规范表示“int256”。
	Sig string
	// ID returns the canonical representation of the method's signature used by the
	// abi definition to identify method names and types.
	// ID 返回方法签名的规范表示，abi 定义使用它来识别方法名称和类型。
	// 它是方法签名的 Keccak256 哈希的前 4 个字节。
	ID []byte
}

// NewMethod creates a new Method.
// A method should always be created using NewMethod.
// It also precomputes the sig representation and the string representation
// of the method.
// NewMethod 创建一个新的 Method。
// 应始终使用 NewMethod 创建方法。
// 它还预先计算了方法的签名表示和字符串表示。
func NewMethod(name string, rawName string, funType FunctionType, mutability string, isConst, isPayable bool, inputs Arguments, outputs Arguments) Method {
	var (
		types       = make([]string, len(inputs))
		inputNames  = make([]string, len(inputs))
		outputNames = make([]string, len(outputs))
	)
	for i, input := range inputs {
		inputNames[i] = fmt.Sprintf("%v %v", input.Type, input.Name)
		types[i] = input.Type.String()
	}
	for i, output := range outputs {
		outputNames[i] = output.Type.String()
		if len(output.Name) > 0 {
			outputNames[i] += fmt.Sprintf(" %v", output.Name)
		}
	}
	// calculate the signature and method id. Note only function
	// has meaningful signature and id.
	// 计算签名和方法 ID。请注意，只有函数具有有意义的签名和 ID。
	var (
		sig string
		id  []byte
	)
	if funType == Function {
		sig = fmt.Sprintf("%v(%v)", rawName, strings.Join(types, ","))
		id = crypto.Keccak256([]byte(sig))[:4]
	}
	identity := fmt.Sprintf("function %v", rawName)
	switch funType {
	case Fallback:
		identity = "fallback"
	case Receive:
		identity = "receive"
	case Constructor:
		identity = "constructor"
	}
	var str string
	// Extract meaningful state mutability of solidity method.
	// If it's empty string or default value "nonpayable", never print it.
	// 提取 Solidity 方法的有意义的状态可变性。
	// 如果它是空字符串或默认值 "nonpayable"，则永远不要打印它。
	if mutability == "" || mutability == "nonpayable" {
		str = fmt.Sprintf("%v(%v) returns(%v)", identity, strings.Join(inputNames, ", "), strings.Join(outputNames, ", "))
	} else {
		str = fmt.Sprintf("%v(%v) %s returns(%v)", identity, strings.Join(inputNames, ", "), mutability, strings.Join(outputNames, ", "))
	}

	return Method{
		Name:            name,
		RawName:         rawName,
		Type:            funType,
		StateMutability: mutability,
		Constant:        isConst,
		Payable:         isPayable,
		Inputs:          inputs,
		Outputs:         outputs,
		str:             str,
		Sig:             sig,
		ID:              id,
	}
}

// String returns the string representation of the method.
// String 返回方法的字符串表示形式。
func (method Method) String() string {
	return method.str
}

// IsConstant returns the indicator whether the method is read-only.
// IsConstant 返回该方法是否为只读的指示器。
// 它会检查 StateMutability 是否为 "view" 或 "pure"，或者旧版的 Constant 标志是否为 true。
func (method Method) IsConstant() bool {
	return method.StateMutability == "view" || method.StateMutability == "pure" || method.Constant
}

// IsPayable returns the indicator whether the method can process
// plain ether transfers.
// IsPayable 返回该方法是否可以处理纯以太币转账的指示器。
// 它会检查 StateMutability 是否为 "payable"，或者旧版的 Payable 标志是否为 true。
func (method Method) IsPayable() bool {
	return method.StateMutability == "payable" || method.Payable
}
